### ISSUE TITLE
MSVC compatibility

### ISSUE THREAD

**Issue by kornelski** [medek/nasm-rs#12]
The msvc target uses `lib` rather than `ar` to compose objects into static library.

It requires:

* cc crate, because it has a helper function necessary to find Visual Studio path, to locate `lib.exe`
* running `lib.exe /out:*.lib *.o` instead of `ar crus`

Would you be interested in PR for this?

**Comment by Boscop** [comment]
Any update on this? :)

**Comment by kornelski** [comment]
The workaround is to make the library using [the `cc` crate](https://crates.rs/crates/cc):

```rust
let mut cc = cc::Build::new();
for o in nasm.compile_objects() {
    cc.object(o);
}
cc.compile("yourlib");
```

**Comment by kornelski** [comment]
The workaround is to make the library using the `cc` crate:

```rust
let mut cc = cc::Build::new();
for o in nasm.compile_objects() {
    cc.object(o);
}
cc.compile("yourlib");
```
