### ISSUE TITLE
Update to rayon 1.0

### ISSUE THREAD

**Issue by Boscop** [medek/nasm-rs#19]
When I try to use `mozjpeg-sys = "0.5.11"` in the same project as `jpeg-decoder = "0.1.14"` I get:
```
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: failed to select a version for `rayon-core` (required by `rayon`):
all possible versions conflict with previously selected versions of `rayon-core`
  version 1.3.0 in use by rayon-core v1.3.0
  possible versions to select: 1.4.0
```
Because jpeg-decoder depends on rayon 1.0 but mozjpeg-sys's build.rs depends on nasm-rs which depends on rayon 0.9

**Comment by medek** [comment]
I merged #18. Which should fix the problem
