### ISSUE TITLE
Does not work with msvc archiver

### ISSUE THREAD

**Issue by tdaede** [medek/nasm-rs#20]
MSVC targets don't have "ar", but "lib" instead. lib unfortunately has different command-line arguments, so it can't be used as a drop in replacement for ar.

**Comment by kornelski** [comment]
It's an old bug: #12

The workaround is to make the library using the `cc` crate:

```rust
let mut cc = cc::Build::new();
for o in nasm.compile_objects() {
    cc.object(o);
}
cc.compile("yourlib");
```

**Comment by tdaede** [comment]
My PR to fix this was actually just merged.
