### ISSUE TITLE
Set -Fdwarf if the rust project is compiled with -C debuginfo=

### ISSUE THREAD

**Issue by cryptomilk** [medek/nasm-rs#25]
Hi,

I don't know if this is possible but nasm-rs should evaluate the rust command line options and if `-C debuginfo=X` is set turn on debug symbols an use `-Fdwarf`.

**Comment by cryptomilk** [comment]
This is required for Linux distributions to generate debuginfo packages.

**Comment by lu-zero** [comment]
https://github.com/medek/nasm-rs/pull/26 should address it
