### ISSUE TITLE
This version of NASM is too old

### ISSUE THREAD

**Issue by TheRadioGuy** [medek/nasm-rs#30]
Hi there, my OS is Windows 10, I've installed nasm from [there](https://www.nasm.us/pub/nasm/releasebuilds/2.14rc16/win64/).

But when I try to compile I get `--- stdout
cargo:rustc-cfg=nasm_x86_64
--- stderr
thread 'main' panicked at 'This version of NASM is too old: No such file or directory (os error 2)', C:\Users\DuckerMan\.cargo\registry\src\github.com-1ecc6299db9ec823\nasm-rs-0.1.7\src\lib.rs:301:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

**Comment by medek** [comment]
The "No file or directory" means that it can't locate a nasm executable in %PATH%. Add where nasm.exe is to your %PATH% environment variable and it should find it just fine.
