### ISSUE TITLE
Incompatible with Xcode's nasm

### ISSUE THREAD

**Issue by kornelski** [medek/nasm-rs#7]
On macOS latest Xcode ships something that looks like a 10-year-old fork of `nasm`, and it's first in `$PATH`, so it gets used even if a newer (homebrew) nasm is installed, and it doesn't use the same type names as later nasm:

> nasm: fatal: unrecognised output format `macho64' - use -hf for a list

<details>

```
$ /Applications/Xcode.app/Contents/Developer/usr/bin/nasm -v
NASM version 0.98.40 (Apple Computer, Inc. build 11) compiled on Oct 24 2017

$ /Applications/Xcode.app/Contents/Developer/usr/bin/nasm -hf
usage: nasm [-@ response file] [-o outfile] [-f format] [-l listfile]
            [options...] [--] filename
    or nasm -r   for version info (obsolete)
    or nasm -v   for version info (preferred)

    -t          assemble in SciTech TASM compatible mode
    -g          generate debug information in selected format.
    -e          preprocess only (writes output to stdout by default)
    -a          don't preprocess (assemble only)
    -M          generate Makefile dependencies on stdout

    -E<file>    redirect error messages to file
    -s          redirect error messages to stdout

    -F format   select a debugging format

    -I<path>    adds a pathname to the include file path
    -O<digit>   optimize branch offsets (-O0 disables, default)
    -P<file>    pre-includes a file
    -D<macro>[=<value>] pre-defines a macro
    -U<macro>   undefines a macro
    -X<format>  specifies error reporting format (gnu or vc)
    -w+foo      enables warnings about foo; -w-foo disables them
where foo can be:
    macro-params            macro calls with wrong no. of params (default off)
    macro-selfref           cyclic macro self-references (default off)
    orphan-labels           labels alone on lines without trailing `:' (default off)
    number-overflow         numeric constants greater than 0xFFFFFFFF (default on)
    gnu-elf-extensions      using 8- or 16-bit relocation in ELF, a GNU extension (default off)

response files should contain command line parameters, one per line.

valid output formats for -f are (`*' denotes default):
  * bin       flat-form binary files (e.g. DOS .COM, .SYS)
    aout      Linux a.out object files
    aoutb     NetBSD/FreeBSD a.out object files
    coff      COFF (i386) object files (e.g. DJGPP for DOS)
    elf       ELF32 (i386) object files (e.g. Linux)
    as86      Linux as86 (bin86 version 0.3) object files
    obj       MS-DOS 16-bit/32-bit OMF object files
    win32     Microsoft Win32 (i386) object files
    rdf       Relocatable Dynamic Object File Format v2.0
    ieee      IEEE-695 (LADsoft variant) object file format
    macho     NeXTstep/OpenStep/Rhapsody/Darwin/MacOS X object files
```

</details>

 ----

I think it'd be best to work around it. Xcode's `nasm` is so bad, that it's not salvageable.

**Comment by jrasky** [comment]
I'd suggest changing your path, maybe even for just that process.

**Comment by kornelski** [comment]
I'm running build from Xcode's "external build system" target, so it sets the path for me and doesn't give an option to override it :(

**Comment by jrasky** [comment]
There's ways to do it: https://stackoverflow.com/questions/4044314/how-do-you-change-the-path-used-in-an-external-makefile-build-using-xcode

Short of that, the better thing to do is probably to have some configuration option to specify an absolute path for nasm at some point. Supporting a very outdated fork of nasm doesn't seem like a great option.

**Comment by kornelski** [comment]
OK. How about searching the path the "hard way" for a supported version?

i.e.

1. Launch `nasm -v`, if it returns `NASM version 0.`, then:
2. `for path in env::split_paths(env::var("PATH"))`
3. see if `path.join("nasm")` is a supported version

**Comment by jrasky** [comment]
Re-implementing PATH seems like an even worse decision. Even the JVM can't get it completely right. Honestly, the best thing to do is probably to provide some mechanism by which a build script can specify a location for nasm. That way the build script can branch on the OS version, and do whatever searching is required. I'll give a stab at writing that change tomorrow, it shouldn't be anything too crazy.

**Comment by kornelski** [comment]
I've made a PR #9 for overriding nasm executable.

**Comment by medek** [comment]
Merged PR#9 should we consider the issue closed?

**Comment by kornelski** [comment]
I'd like to discuss the solution I proposed (PR #10). 

I'm not aware how JVM gets path wrong. 

The PR first tries "nasm" command as usual — relying on system implementation of PATH. It uses custom search only if normal command fails, so I don't think it can break anything. The custom path behavior is only part of error recovery.

The advantage is that it "just works" without the build script needing to do the same. Since Xcode problem is obscure, I think it's nice to keep it as implementation detail and not require everyone else to be aware of it and fix it themselves.

**Comment by kornelski** [comment]
This is still a pain point that needs fixing.

**Comment by medek** [comment]
Are you just calling a script from xcode to compile the source?

Can you detail the configuration you're using to do this?

**Comment by kornelski** [comment]
I'm calling `cargo build` from `External Build System` target. 

This makes Xcode launch cargo in its tightly controlled environment, with `PATH` and other env vars set up. This is for the most part a *good thing*, because it helps `-sys` crates find appropriate versions of libraries, configures linker for the right SDK version, etc.

**Comment by kornelski** [comment]
BTW, Xcode's own nasm is old and busted, so I'm not suggesting to support it (even if nasm-rs supported Xcode's nasm, it wouldn't be useful to me, since Xcode's old version can't compile any interesting projects).

The key problem is that Xcode's nasm gets in the way of *good* version of nasm from Homebrew.

**Comment by medek** [comment]
Yeah, why not just wrap it in a script?

like:
```
#!

PATH="/usr/local/bin:$CARGO_PATH" cargo build
```
Change the build command to bash with the script as an argument and put the following in your ```.bashrc```.
```
export CARGO_PATH="$HOME/.cargo/bin" #or wherever it is
```

Or you can put the path walking stuff in your ```build.rs``` and set that path via ```Build.nasm```. Really this is a configuration problem with XCode and I don't want to add code that's out of scope.

**Comment by kornelski** [comment]
I would rather not change `PATH`, because this affects all tools, not just `nasm`.

I can work around this in `Build.nasm`, but so will have every `nasm-rs`-using script that wants to be compatible with Xcode's environment. The advantage of centralized package like this is that it can apply a workaround once, for everyone.

**Comment by medek** [comment]
If you don't want to change ```PATH``` to the above subset, just reorder it so ```/usr/local/bin``` is at the start:

```
PATH="/usr/local/bin:$PATH" cargo build
```
That way you'll get the right nasm, and everything else is still there.

**Comment by kornelski** [comment]
No, I mean everything else launched *from within Cargo* build scripts. Cargo's sys crates can run arbitrary commands.

**Comment by medek** [comment]
Yes, so instead of just a subset of ```PATH``` that I suggested first script you're just making it so ```/usr/local/bin``` is checked [first](http://friendly-101.readthedocs.io/en/latest/bashprofile.html#understanding-your-path) in the second.

**Comment by kornelski** [comment]
But that prioritizes *all* of `/usr/local/bin`, not just `/usr/local/bin/nasm` as the only exception.

**Comment by tom-dignan** [comment]
After you install nasm with homebrew, don't forget to open a new shell, or you'll still be invoking the old nasm.

**Comment by kornelski** [comment]
@medek You need to keep in mind that prefixing Xcode's path with something else breaks *other* things, e.g. I want Xcode's compiler, not Homebrew's compiler, but at the same time I want Homebrew's nasm, not Xcode's nasm:

* `/a/cc`  # good
* `/a/nasm` # bad
* `/b/cc` # bad
* `/b/nasm` # good

and I need to run both good `cc` and good `nasm` as part of one invocation of one `cargo build` command that only allows one value of `PATH`. `PATH=/a:/b` will pick wrong `nasm`, and `PATH=/b:/a` will pick wrong `cc`.
